### PR TITLE
Fix/issues/24 update

### LINKED ISSUE #24: Fix : Ant design console error

### PR DESCRIPTION
**Pull request by HlainePoeEi**
- create room list page
- create room page
- add nanoid package in frontend
- remove uuid package in frontend

Resolve #24

### CODE REVIEW

File: frontend/src/components/Room/Room.js [hunk 1]
```diff
@@ -0,0 +1,339 @@
...
+    const peersRef = useRef([]);
+    const room = useParams();
+    const videoConstraints = {
+        minAspectRatio: 1.333,
+        minFrameRate: 60,
+        height: window.innerHeight / 1.8,
+        width: window.innerWidth / 2,
+    };
+    useEffect(() => {
+        socketRef.current = io(signalServerUrl);
```
Comment (myonaingwinn) [inline frontend/src/components/Room/Room.js:96]: Delete this line and use ```line no 13 : socket = io(....```

File: frontend/src/index.js [hunk 2]
```diff
@@ -4,12 +4,15 @@ import "antd/dist/antd.min.css";
...
 const root = ReactDOM.createRoot(document.getElementById("root"));
 root.render(
-    <React.StrictMode>
-        <App />
-    </React.StrictMode>
+    // <React.StrictMode>
+        <BrowserRouter>
+            <App />
+        </BrowserRouter>
+    // </React.StrictMode>
```
Comment (myonaingwinn) [inline frontend/src/index.js:15]: Please uncomment line no 11 and 15
```suggestion
    <React.StrictMode>
        <BrowserRouter>
            <App />
        </BrowserRouter>
    </React.StrictMode>
```

File: frontend/src/components/Room/RoomData.js [hunk 3]
```diff
@@ -0,0 +1,63 @@
+import { Button, Col, Card, Row } from "antd";
+import { useNavigate } from "react-router-dom";
+import io from "socket.io-client";
+import React, { useState, useEffect } from "react";
+import { UserOutlined } from "@ant-design/icons";
+
+const socket = io("http://localhost:5000");
```
Comment (myonaingwinn) [inline frontend/src/components/Room/RoomData.js:7]: Please use VariableURL

File: frontend/src/components/Room/RoomData.js [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+
+const RoomData = () => {
```
Comment (myonaingwinn) [inline frontend/src/components/Room/RoomData.js:9]: RoomComponent

File: frontend/src/components/Room/RoomList.js [hunk 5]
```diff
@@ -1,73 +1,20 @@
...
-                                        </div>
-                                        <div style={{ marginTop: "5px" }}>
-                                            <UserOutlined /> {roomList[key].usersInRoom.length}
-                                        </div>
-                                    </Card>
-                                </Col>
-                            );
-                        })}
-                </Row>
+                <RoomData />
```
Comment (myonaingwinn) [inline frontend/src/components/Room/RoomList.js:17]: RoomComponent

**Review by myonaingwinn — APPROVED** [review]

**Review by myonaingwinn — APPROVED** [review]
